[package]
name = "tests_with_diesel_cli"
version = "0.1.0"
authors = ["Alex Whitney <adwhit@fastmail.com>"]
edition = "2021"

[dependencies]
diesel = { version = "2.1.0", features = ["postgres"] }
diesel-derive-enum = { path = "./..", features = ["postgres"]}

[features]
custom = []
